### ISSUE TITLE
Some tagged places on google map won't return needed id

### ISSUE THREAD

**Issue by T1m1** [locator-kn/web#133] opened 2015-07-11 17:26 UTC
![image](https://cloud.githubusercontent.com/assets/5616884/8634675/a4b361c6-2802-11e5-9918-dcece7a57b70.png)

**Comment by T1m1** [comment] 2015-07-11 17:27
![image](https://cloud.githubusercontent.com/assets/5616884/8634681/dae7b35a-2802-11e5-8cb4-62000221caad.png)

**Comment by timoweiss** [comment] 2015-07-11 17:29
what means "loading a location image twice"?

**Comment by T1m1** [comment] 2015-07-11 17:29
1. load image 
2. load other image 
3. try to create

**Comment by timoweiss** [comment] 2015-07-11 17:30
upload?

**Comment by T1m1** [comment] 2015-07-11 17:31
yes

**Comment by timoweiss** [comment] 2015-07-11 17:39
cant reproduce

**Comment by michaelknoch** [comment] 2015-07-11 17:40
works for me. found another bug where budget will be set during image upload.
fixed in 4a5428728440d1240a4f404d9e0cc3b481582c68

**Comment by timoweiss** [comment] 2015-07-11 17:40
:dancer:

**Comment by T1m1** [comment] 2015-07-11 17:45
I can reproduce it. 
1. Select image and upload 
2. Select image and do not upload
3. select image and upload
4. enter title, description (all 300 letters) , and "imperia ... " form search field
5. Try to save -> bad request (PUT 400)
   ![image](https://cloud.githubusercontent.com/assets/5616884/8634735/5050dd90-2805-11e5-894d-1d580f9f0967.png)

**Comment by T1m1** [comment] 2015-07-11 17:46
Imperia has no city.title

**Comment by michaelknoch** [comment] 2015-07-11 19:06
The request to google returns no locality with place.id. Every other location (Statue of liberty f.e.) works fine.
A possible workaround for this edge case could be an additional request to get the place.id by city name.

**Comment by SteffenGorenflo** [comment] 2015-07-12 15:42
if no place id is emitted, a request from backend to google is made to resolve the place id

**Closed as completed** 2015-07-17 22:25 UTC
Labels: bug
